name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain:1-bookworm-slim-node22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Restore NPM node_modules
        uses: actions/cache/restore@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install node_modules
        run: |
          sudo corepack enable
          yarn install
      - name: Cache NPM dependencies
        uses: actions/cache@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.CDK_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
      - name: Run build
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
          CDK_DEPLOY_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
        run: yarn run ci:gha
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          directory: coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run Package
        run: yarn run jsii:pacmak:parallel
