name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain:1-bookworm-slim-node22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install pnpm and dependencies
        run: |
          sudo corepack enable
          sudo corepack prepare pnpm@latest --activate
          pnpm install
      - name: Cache NPM dependencies
        uses: actions/cache@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Assume role using AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CDK_DEPLOY_REGION }}
      - name: Run build
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
          CDK_DEPLOY_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
        run: pnpm run ci:gha
      - name: Run Package
        run: pnpm run jsii:pacmak:parallel
